services:
  nut-exporter:
    image: hon95/prometheus-nut-exporter:1
    container_name: nut-exporter
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      HTTP_PATH: /metrics
    ports:
      - "9995:9995"
  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.listen-address=0.0.0.0:9090
    volumes:
      - ./prometheus/config:/etc/prometheus:ro
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:13.2.2
    container_name: grafana
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      GF_FEATURE_TOGGLES_ENABLE: vizActions
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3001:3000"
