services:
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:13
    container_name: forgejo-runner
    restart: unless-stopped
    user: root
    working_dir: /data
    command: forgejo-runner daemon
    volumes:
      - /opt/stacks/forgejo-runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
