x-logging: &logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  wol-bot:
    build: .
    image: local/discord-bots:1
    container_name: wol-bot
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    env_file: wol-bot/.env
    volumes:
      - ./wol-bot/bot.py:/app/bot.py:ro
    logging: *logging
