- name: daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: restart nut-monitor
  ansible.builtin.systemd_service:
    name: nut-monitor
    state: restarted

- name: apply sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.d/90-mtu-probing.conf
  changed_when: true

- name: update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true

- name: restart nut-server
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  loop: [nut-driver@apc500.service, nut-server.service]
